version: '3.7'
services:
  cip:
    image: luninfoparco/awscip:latest
    environment:
      - AWS_ACCESS_KEY_ID=your_aws_access_key_id
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_access_key
      - AWS_REGION=your_aws_region
      - AWS_ZONE_ID=your_aws_zone_id
    volumes:
      - ./domains.list:/scripts/domains.list
      - ./log:/scripts/logs
