apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "awscip-chart.fullname" . }}-cip-domains-list
  labels:
  {{- include "awscip-chart.labels" . | nindent 4 }}
data:
  domains.list: {{ .Values.cipDomainsList.domainsList | toYaml | indent 1 }}