apiVersion: v1
kind: Secret
metadata:
  name: {{ include "awscip-chart.fullname" . }}-secret
  labels:
  {{- include "awscip-chart.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ required "secret.awsAccessKeyId is required" .Values.secret.awsAccessKeyId
    | b64enc | quote }}
  AWS_REGION: {{ required "secret.awsRegion is required" .Values.secret.awsRegion
    | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required "secret.awsSecretAccessKey is required" .Values.secret.awsSecretAccessKey
    | b64enc | quote }}
  AWS_ZONE_ID: {{ required "secret.awsZoneId is required" .Values.secret.awsZoneId
    | b64enc | quote }}
type: Opaque