name: docker-multiple-arch

on:
  schedule:
    - cron: '0 0 * * SUN'
  push:
    paths:
      - "Dockerfile.dockerhub"
      - "**.sh"
      - "**.yml"
    branches: 
      - "main"
      - "dev/kubernetes"


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        if: github.ref == 'refs/heads/dev/kubernetes'
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.dockerhub
          platforms: linux/amd64,linux/arm64
          push: true
          tags: luninfoparco/awscip:dev